name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ ubuntu-latest, windows-latest, macos-latest ]
        toolchain: [ stable, beta, 1.7.0 ]
        exclude:
          - platform: windows-latest
            toolchain: 1.7.0
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Install Rust ${{ matrix.toolchain }} toolchain
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile=minimal --default-toolchain ${{ matrix.toolchain }}
          rustup override set ${{ matrix.toolchain }}
      - name: Install no-std-check dependencies for ARM Embedded
        if: "matrix.platform == 'ubuntu-latest'"
        run: |
          rustup target add thumbv7m-none-eabi
          sudo apt-get -y install gcc-arm-none-eabi
          sudo apt-get -y install gcc-arm-none-eabi
      - name: Build server
        run: cargo build